name: GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: pragati-2024
          template: classic
          base: header, activity, community, repositories, metadata
          filename: github-stats.svg
          config_timezone: Asia/Kolkata
          config_padding: 10
          optimize: svg
